/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/Navigation/AppBar/AppBar.vue')['default']
    CampaignCollapsable: typeof import('./components/Layout/CampaignCollapsable/CampaignCollapsable.vue')['default']
    CampaignSelection: typeof import('./components/Navigation/AppBar/CampaignSelection.vue')['default']
    CollapsableItemsCard: typeof import('./components/Common/Card/CollapsableItemsCard.vue')['default']
    DiaryCard: typeof import('./components/Diary/DiaryCard.vue')['default']
    InformationItem: typeof import('./components/Common/InformationItem.vue')['default']
    NavigationGradient: typeof import('./components/Navigation/AppBar/NavigationGradient.vue')['default']
    NonPlayerCharactersCard: typeof import('./components/Characters/NonPlayerCharactersCard.vue')['default']
    PlayerCharactersCard: typeof import('./components/Characters/PlayerCharactersCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./components/test.vue')['default']
  }
}
